deploy:
#	mv ${HOME}/.bashrc ${HOME}/.bashrc_backup_$(shell date +%s)
#	mv ${HOME}/.bash_aliases ${HOME}/.bash_aliases_backup_$(shell date +%s)
	ln -s ${PWD}/bashrc ${HOME}/.bashrc
	ln -s ${PWD}/bash_aliases ${HOME}/.bash_aliases
